name: Build

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  Build:
    runs-on: macos-latest
    steps:
      - name: os fetch
        run : |
          brew install neofetch
          neofetch
      - name: clone
        run: |
          git clone --recursive https://github.com/xem8k5/animdustry/
      - name: Nim
        run: |
          brew install nim
      - name: Set Up
        run: |
          export PATH="~/.nimble/bin:$PATH"
          source ~/.bashrc
          cd animdustry
          nimble install -y -d
      - name: Build Mac
        run: |
          export PATH="~/.nimble/bin:$PATH"
          source ~/.bashrc
          cd animdustry
          nimble deploy
      - name: Upload to Build branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: Build
          build_dir: ./animdustry/build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
