name: Build Windows

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  Build_Windows:
    runs-on: windows-latest
    steps:
      - name: clone
        run: |
          git clone --recursive https://github.com/PCX-LK/animbean
      - name: Nim
        uses: iffy/install-nim@v4.1.3
      - name: Set Up
        run: |
          cd animbean
          nimble install -y -d
      - name: Build Windows
        run: |
          cd animbean
          nimble deploy
      - name: Upload to Build branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: build-windows
          build_dir: ./animbean/build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
