name: Build Android

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  Build_Android:
    runs-on: Ubuntu-latest
    steps:
      - name: os fetch
        run: |
          sudo apt install neofetch -y
          neofetch
      - name: clone
        run: |
          git clone --recursive https://github.com/xem8k5/animdustry/
#      - name: Set up JDK 1.8
#        uses: actions/setup-java@v3
#        with:
#          java-version: 1.8
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r21e
      - name: Nim
        uses: iffy/install-nim@v4.1.3
      - name: Set Up
        run: |
          cd animbean
          nimble install -y -d
      - name: Build Android
        run: |
          cd animbean
          nimble androidPackage
      - name: Upload to Build branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: build-android
          build_dir: ./animbean/android/build/outputs/apk/debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
